### ISSUE TITLE
Dosbox Staging Natively Supports MT32 Emulation

### ISSUE THREAD

**Issue by MasterO2** [ericvids/wolfmidi#1]
@ericvids 

This is not an issue, but I figured you'd want to know. 

Just so you know, https://dosbox-staging.github.io/ natively supports MT32 emulation:

https://dosbox-staging.github.io/v0-77-0/#2-significant-changes

https://github.com/dosbox-staging/dosbox-staging/wiki/MIDI#mt32emu

Github Page: https://github.com/dosbox-staging/dosbox-staging

Dosbox Staging's Discord: https://discord.gg/WwAg3Xf

**Comment by ericvids** [comment]
Currently wolfmidi is made for General MIDI (Roland Sound Canvas and later) so the benefit from using DOSBox-baked Roland MT32 emulation is limited (unless there is a way to automatically apply the MT2GM patch).  But thanks for the note!
