### ISSUE TITLE
ECWolf playback issue

### ISSUE THREAD

**Issue by NightFright2k19** [ericvids/wolfmidi#3]
When I load wolfmidi.zip via ECWolf (latest version, v1.4.1), all I get are incoherent notes. Has anything changed regarding how the MIDI files are loaded in general? If I load regular .MID files, it seems to work fine.

**Comment by ericvids** [comment]
Hi, have you tested with changing the "Music Device & Volume" option in Sound Options?  I've noticed that in the latest ECWolf, it should be changed from AdLib/Sound Blaster to SDL_mixer MIDI Synth.  (Note that this uses your default MIDI device, which is usually Microsoft GS Wavetable Synth unless you use a program like CoolSoft MIDIMapper to change it.)

Let me know if this works for you so I can update the instructions.

If you are asking about getting AdLib/SB-like music (i.e., still MIDI but rendered via OPL2/3), wolfmidi unfortunately doesn't support that.

**Comment by NightFright2k19** [comment]
That did the trick! 
TBH I never touched this section of the menu before since everything worked out of the box. I had been using a different MIDI mod before and that one worked fine with the default AdLib choice.

I would recommend adding this info not only to the general instructions, but also the release notes. The full menu path in ECWolf is: "Options" > "Sound Options" > "Music Device & Volume" > "SDL_mixer"

Thanks a lot for the fast support!
